### PR TITLE
ctp-common: use power driver from fugu

### PR DESCRIPTION
**Pull request by tank0412**
DT2W is OK, but healthd is broken in ramdisk.

### CODE REVIEW

**Comment by artefvck** [comment]
stay here, we will consider this

**Comment by dgadelha** [comment]
Unnecessary.

**Comment by tank0412** [comment]
On my phone battery life is really improved.
dgadelha, lets i mark your every commit unnecessary....

**Comment by artefvck** [comment]
I think this will affect performance

**Comment by dgadelha** [comment]
This will not affect performance, it's just a tweak for the `interactive` governor.

It will just tweak boostpulse, which is safe to keep at the default values.

[android_kernel_asus_T00F/Documentation/cpu-freq/governors.txt](https://github.com/Zenfone-Dev/android_kernel_asus_T00F/blob/cm-13.0/Documentation/cpu-freq/governors.txt):

```
boost: If non-zero, immediately boost speed of all CPUs to at least
hispeed_freq until zero is written to this attribute.  If zero, allow
CPU speeds to drop below hispeed_freq according to load as usual.
Default is zero.

boostpulse: On each write, immediately boost speed of all CPUs to
hispeed_freq for at least the period of time specified by
boostpulse_duration, after which speeds are allowed to drop below
hispeed_freq according to load as usual.

boostpulse_duration: Length of time to hold CPU speed at hispeed_freq
on a write to boostpulse, before allowing speed to drop according to
load as usual. Default is 80000 uS.
```

**Comment by artefvck** [comment]
do you know we implement this ?? https://github.com/Zenfone-Dev/android_kernel_asus_T00F/commit/42e99af440f78e5f049146f95d7905dc6cf1e866

then turn it into ondemand
https://github.com/Zenfone-Dev/android_device_asus_ctp-common/commit/5688f013c8908545e0af6f8caea2bff579a47d0f

**Pull request closed without merging**
